Las mejores practicas

In [42]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=0, copy=True)
# Represent the unknown value by np.nan in numpy
data_origin = [[30, 100],
               [20, 50],
               [35, np.nan],
               [25, 80],
               [30, 70],
               [40, 60]]
 #Imputation with the mean value
imp_mean = SimpleImputer(missing_values='NaN', strategy='mean')
imp_mean.fit(data_origin)
imp_mean.fit(data_origin)
new = [[20, np.nan],
       [30, np.nan],
       [np.nan, 70],
       [np.nan, np.nan]]
new_mean_imp = imp_mean.transform(new)
print(new_mean_imp)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

Guardar, cargar y reusar modelos.

In [46]:
from sklearn import datasets
dataset = datasets.load_diabetes()
X_full, y = dataset.data, dataset.target
#Simulate a corrupted data set by adding 25% missing values
m, n = X_full.shape
m_missing = int(m * 0.25)
print(m, m_missing)
#Randomly select m_missing samples
np.random.seed(42)
missing_samples = np.array([True] * m_missing +
[False] * (m - m_missing))
np.random.shuffle(missing_samples)
# For each missing sample, randomly select 1 out of n features
missing_features = np.random.randint(low=0, high=n,
size=m_missing)
# Represent missing values by nan
X_missing = X_full.copy()
X_missing[np.where(missing_samples)[0], missing_features] = X_rm_missing = X_missing[~missing_samples, :] y_rm_missing = y[~missing_samples]

SyntaxError: invalid syntax (<ipython-input-46-f4298089e29d>, line 18)

In [47]:
from sklearn.datasets import load_digits
dataset = load_digits()
X, y = dataset.data, dataset.target
print(X.shape)

(1797, 64)


In [48]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
classifier = SVC(gamma=0.005)
score = cross_val_score(classifier, X, y).mean()
print('Score with the original data set: {0:.2f}'.format(score))

Score with the original data set: 0.90


In [70]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=100, criterion='
  random_forest.fit(X, y)
feature_sorted = np.argsort(random_forest.feature_importances_)

SyntaxError: EOL while scanning string literal (<ipython-input-70-726fa2696b2b>, line 2)

In [55]:
from sklearn.preprocessing import Binarizer
X = [[4], [1], [3], [0]]
binarizer = Binarizer(threshold=2.9)
X_new = binarizer.fit_transform(X)
print(X_new)

[[1]
 [0]
 [1]
 [0]]


In [56]:
from sklearn.preprocessing import PolynomialFeatures
X = [[2, 4],
     [1, 3],
     [3, 2],
     [0, 3]]
poly = PolynomialFeatures(degree=2)
X_new = poly.fit_transform(X)
print(X_new)

[[ 1.  2.  4.  4.  8. 16.]
 [ 1.  1.  3.  1.  3.  9.]
 [ 1.  3.  2.  9.  6.  4.]
 [ 1.  0.  3.  0.  0.  9.]]


In [58]:
dataset = datasets.load_diabetes()
X, y = dataset.data, dataset.target
num_new = 30 # the last 30 samples as new data set
X_train = X[:-num_new, :]
y_train = y[:-num_new]
X_new = X[-num_new:, :]
y_new = y[-num_new:]

In [59]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [60]:
import pickle
pickle.dump(scaler, open("scaler.p", "wb" ))

In [61]:
X_scaled_train = scaler.transform(X_train)
from sklearn.svm import SVR
regressor = SVR(C=20)
regressor.fit(X_scaled_train, y_train)

SVR(C=20, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [62]:
pickle.dump(regressor, open("regressor.p", "wb"))

In [63]:
my_scaler = pickle.load(open("scaler.p", "rb" ))
my_regressor = pickle.load(open("regressor.p", "rb"))

In [64]:
X_scaled_new = my_scaler.transform(X_new)
predictions = my_regressor.predict(X_scaled_new)

In [ ]:
Performance de monitor modelo

In [71]:
from sklearn.metrics import r2_score
print('Health check on the model, R^2: {0:.3f}'.format(r2_score(y_new, predictions)))

Health check on the model, R^2: 0.613
